# 基础镜像
FROM redis
# author
MAINTAINER andy

# 挂载目录
VOLUME /home/andy/redis
# 创建目录
RUN mkdir -p /home/andy/redis
# 指定路径
WORKDIR /home/andy/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/andy/redis/redis.conf
