# 基础镜像
FROM nginx
# author
MAINTAINER andy

# 挂载目录
VOLUME /home/andy/projects/andy-ui
# 创建目录
RUN mkdir -p /home/andy/projects/andy-ui
# 指定路径
WORKDIR /home/andy/projects/andy-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/andy/projects/andy-ui
