# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER andy

# 挂载目录
VOLUME /home/andy
# 创建目录
RUN mkdir -p /home/andy
# 指定路径
WORKDIR /home/andy
# 复制jar文件到路径
COPY ./jar/andy-gateway.jar /home/andy/andy-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","andy-gateway.jar"]